---
- name: Configure Kubernetes Cluster 
  become: yes
  hosts : 
    - controllers
    - workers 
  roles : 
    - apt_setup
    - k8s_install
  vars : 
    controllers_group : controllers
    workers_group : workers